version: '3'

services:
    server:
        build:
            context: ./
        ports:
            - "80:80"

    db:
        image: mysql:8.0.17
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: testapp
        ports:
            - "3308:3306"

    admin:    
        image: adminer    
        ports:      
            - "8080:8080"