version: '3'

services:
    server:
        build:
            context: ./
        ports:
            - "80:80"

    db:
        image: mysql:8.0.17
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
# Names our volume
volumes:
    my-db:
    #docker run --name my-db --volumes-from my-db -e MYSQL_ROOT_PASSWORD='password' -p 3307:3306 mysql

